[package]
name = "dirty-panics-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.dirty-panics]
path = ".."

[[bin]]
name = "oracle_message"
path = "fuzz_targets/oracle_message.rs"
test = false
doc = false
bench = false
